### PR TITLE
style(frontend): object-curly-spacing -> always

### PR DESCRIPTION
**Pull request by davezuko**
This improves readability, abides by the airbnb guide, and also keeps us in line with how the backend structures their code.

### CODE REVIEW

**Comment by kyleturco** [comment]
🤖

**Comment by jhabdas** [comment]
Regardless of what we decide on this rule (I still have no opinion) I'm :+1: for consistency throughout the codebase. And if we do go for it, I would prefer we wait until post-MVP to refactor.

Also, if consistent with BE, wouldn't this be moved to `organisation` rules?

**Comment by davezuko** [comment]
@jhabdas yeah it could probably just live there. It _is_ a fixable rule (`npm run lint -- --fix`) so if we did integrate it pre-MVP it would be a super fast change, but it's not urgent at all so I don't have much of an opinion. Important features come first :)

**Comment by levithomason** [comment]
:accept:

**Comment by levithomason** [comment]
merging, this was already voted on

**Pull request merged**
